import { Box, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import Footer from "src/components/Footer";
import Header from "src/components/Header";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Next Chakra Starter TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box role="main" bg="gray.100">
        <Header />

        <Box p="5">
          <Text>Content</Text>
        </Box>
      </Box>

      <Footer />
    </Box>
  );
};

export default Home;
